package ab3d2.data;

/**
 * Traduction littérale de ab3d2_source/data/version.i
 * "Generated by bumprev.py, do not edit"
 *
 * L'original émet une chaîne $VER: dans le binaire, choisie par les symboles
 * de compilation DEV / OPT060 / OPT040. Le port Java correspond à la lignée
 * générique 68030+ ; les deux variantes (dev / release) sont conservées.
 */
public final class Version {

    public static final String VER_DEV_060 = "$VER: tkg 1.0 (15.11.2025) 68060 development build #12, commit:99495ed";
    public static final String VER_DEV_040 = "$VER: tkg 1.0 (15.11.2025) 68040 development build #12, commit:99495ed";
    public static final String VER_DEV_030 = "$VER: tkg 1.0 (15.11.2025) 68030+ development build #12, commit:99495ed";

    public static final String VER_060 = "$VER: tkg 1.0 (15.11.2025) 68060 build #12, commit:99495ed";
    public static final String VER_040 = "$VER: tkg 1.0 (15.11.2025) 68040 build #12, commit:99495ed";
    public static final String VER_030 = "$VER: tkg 1.0 (15.11.2025) 68030+ build #12, commit:99495ed";

    private Version() {
    }
}
