package ab3d2;

/**
 * Traduction littérale de ab3d2_source/defs.i
 *
 * "Structure and limt definitions"
 * DO NOT EDIT THIS FILE WITHOUT MAKING THE CORRESPONDING CHANGES IN c/defs.h
 *
 * Les STRUCTURE de l'ASM deviennent des constantes d'offset (int) : un champ
 * Xxx_w à l'offset N d'une structure pointée par a0 se lit Mem.w(a0 + Xxx_w).
 * Les offsets sont calculés avec les macros standard exec/types.i :
 * UBYTE/BYTE +1, UWORD/WORD +2, ULONG/LONG +4, STRUCT +taille, LABEL +0.
 * Noms conservés verbatim (y compris la coquille TBLT_ dans TLBT).
 */
public final class Defs {

    private Defs() {
    }

    // *****************************
    // * Structure definitions *****
    // *****************************

    public static final int MAX_LEVEL_OBJ_DIST_COUNT = 256 + 32;   // 288
    public static final int MAX_OBJS_IN_LINE_COUNT = 400;
    public static final int LVL_OBJ_DEFINITION_SIZE = 64;          // Runtime size of level object

    public static final int NUM_LEVELS = 16;
    public static final int NUM_BULLET_DEFS = 20;
    public static final int NUM_GUN_DEFS = 10;
    public static final int NUM_ALIEN_DEFS = 20;
    public static final int NUM_OBJECT_DEFS = 30;
    public static final int NUM_SFX = 64;
    public static final int NUM_WALL_TEXTURES = 16;

    // Player Definition (runtime) — STRUCTURE PlrT,0
    // Long fields
    public static final int PlrT_ObjectPtr_l = 0;                  //   0, 4
    public static final int PlrT_XOff_l = 4;                       //   4, 4 - sometimes accessed as w
    public static final int PlrT_YOff_l = 8;                       //   8, 4
    public static final int PlrT_ZOff_l = 12;                      //  12, 4 - sometimes accessed as w
    public static final int PlrT_ZonePtr_l = 16;                   //  16, 4
    public static final int PlrT_Height_l = 20;                    //  20, 4
    public static final int PlrT_AimSpeed_l = 24;                  //  24, 4
    public static final int PlrT_SnapXOff_l = 28;                  //  28, 4
    public static final int PlrT_SnapYOff_l = 32;                  //  32, 4
    public static final int PlrT_SnapYVel_l = 36;                  //  36, 4
    public static final int PlrT_SnapZOff_l = 40;                  //  40, 4
    public static final int PlrT_SnapTYOff_l = 44;                 //  44, 4
    public static final int PlrT_SnapXSpdVal_l = 48;               //  48, 4
    public static final int PlrT_SnapZSpdVal_l = 52;               //  52, 4
    public static final int PlrT_SnapHeight_l = 56;                //  56, 4
    public static final int PlrT_SnapTargHeight_l = 60;            //  60, 4
    public static final int PlrT_TmpXOff_l = 64;                   //  64, 4 - also accessed as w
    public static final int PlrT_TmpZOff_l = 68;                   //  68, 4
    public static final int PlrT_TmpYOff_l = 72;                   //  72, 4

    // Private
    public static final int PlrT_ListOfGraphRoomsPtr_l = 76;       //  76, 4
    public static final int PlrT_PointsToRotatePtr_l = 80;         //  80, 4
    public static final int PlrT_BobbleY_l = 84;                   //  84, 4
    public static final int PlrT_TmpHeight_l = 88;                 //  88, 4
    public static final int PlrT_OldX_l = 92;                      //  92, 4
    public static final int PlrT_OldZ_l = 96;                      //  96, 4
    public static final int PlrT_OldRoomPtr_l = 100;               // 100, 4
    public static final int PlrT_SnapSquishedHeight_l = 104;       // 104, 4
    public static final int PlrT_DefaultEnemyFlags_l = 108;        // 108, 4

    // Word fields
    public static final int PlrT_Energy_w = 112;                   // 112, 2
    public static final int PlrT_CosVal_w = 114;                   // 114, 2
    public static final int PlrT_SinVal_w = 116;                   // 116, 2
    public static final int PlrT_AngPos_w = 118;                   // 118, 2
    public static final int PlrT_Zone_w = 120;                     // 120, 2
    public static final int PlrT_FloorSpd_w = 122;                 // 122, 2
    public static final int PlrT_RoomBright_w = 124;               // 124, 2
    public static final int PlrT_Bobble_w = 126;                   // 126, 2
    public static final int PlrT_SnapAngPos_w = 128;               // 128, 2
    public static final int PlrT_SnapAngSpd_w = 130;               // 130, 2
    public static final int PlrT_TmpAngPos_w = 132;                // 132, 2
    public static final int PlrT_TimeToShoot_w = 134;              // 134, 2

    // This section is saved/loaded in game save
    public static final int PlrT_Health_w = 136;                   // 136, 2
    public static final int PlrT_JetpackFuel_w = 138;              // 138, 2
    public static final int PlrT_AmmoCounts_vw = 140;              // 140, 40 - UWORD[NUM_BULLET_DEFS]
    public static final int PlrT_Shield_w = 180;                   // 180, 2
    public static final int PlrT_Jetpack_w = 182;                  // 182, 2
    public static final int PlrT_Weapons_vb = 184;                 // 184, 20 - UWORD[NUM_GUN_DEFS]

    public static final int PlrT_GunFrame_w = 204;                 // 204, 2
    public static final int PlrT_NoiseVol_w = 206;                 // 206, 2
    // Private
    public static final int PlrT_TmpHoldDown_w = 208;              // 208, 2
    public static final int PlrT_TmpBobble_w = 210;                // 210, 2
    public static final int PlrT_SnapCosVal_w = 212;               // 212, 2
    public static final int PlrT_SnapSinVal_w = 214;               // 214, 2
    public static final int PlrT_WalkSFXTime_w = 216;              // 216, 2

    // Byte data
    public static final int PlrT_Keys_b = 218;
    public static final int PlrT_Path_b = 219;
    public static final int PlrT_Mouse_b = 220;
    public static final int PlrT_Joystick_b = 221;
    public static final int PlrT_GunSelected_b = 222;
    public static final int PlrT_StoodInTop_b = 223;
    public static final int PlrT_Ducked_b = 224;
    public static final int PlrT_Squished_b = 225;
    public static final int PlrT_Echo_b = 226;
    public static final int PlrT_Fire_b = 227;
    public static final int PlrT_Clicked_b = 228;
    public static final int PlrT_Used_b = 229;
    public static final int PlrT_TmpClicked_b = 230;
    public static final int PlrT_TmpSpcTap_b = 231;
    public static final int PlrT_TmpGunSelected_b = 232;
    public static final int PlrT_TmpFire_b = 233;

    // Private
    public static final int PlrT_Teleported_b = 234;
    public static final int PlrT_Dead_b = 235;
    public static final int PlrT_TmpDucked_b = 236;
    public static final int PlrT_StoodOnLift_b = 237;

    public static final int PlrT_InvMouse_b = 238;
    public static final int PlrT_Reserved2_b = 239;

    // Tables
    public static final int PlrT_ObjectDistances_vw = 240;         // 240, MAX_LEVEL_OBJ_DIST_COUNT*2
    public static final int PlrT_ObjectsInLine_vb = 816;           // 816, MAX_OBJS_IN_LINE_COUNT
    public static final int PlrT_SizeOf_l = 1216;

    // Bullet definition — STRUCTURE BulT,0
    public static final int BulT_IsHitScan_l = 0;                  //   0, 4
    public static final int BulT_Gravity_l = 4;                    //   4, 4
    public static final int BulT_Lifetime_l = 8;                   //   8, 4
    public static final int BulT_AmmoInClip_l = 12;                //  12, 4
    public static final int BulT_BounceHoriz_l = 16;               //  16, 4
    public static final int BulT_BounceVert_l = 20;                //  20, 4
    public static final int BulT_HitDamage_l = 24;                 //  24, 4
    public static final int BulT_ExplosiveForce_l = 28;            //  28, 4
    public static final int BulT_Speed_l = 32;                     //  32, 4
    public static final int BulT_AnimFrames_l = 36;                //  36, 4
    public static final int BulT_PopFrames_l = 40;                 //  40, 4
    public static final int BulT_BounceSFX_l = 44;                 //  44, 4
    public static final int BulT_ImpactSFX_l = 48;                 //  48, 4
    public static final int BulT_GraphicType_l = 52;               //  52, 4
    public static final int BulT_ImpactGraphicType_l = 56;         //  56, 4
    public static final int BulT_AnimData_vb = 60;                 //  60, 120
    public static final int BulT_PopData_vb = 180;                 // 180, 120
    public static final int BulT_SizeOf_l = 300;                   // 300

    // Bullet shoot definition — STRUCTURE ShootT,0
    public static final int ShootT_BulType_w = 0;                  // 0, 2
    public static final int ShootT_Delay_w = 2;                    // 2, 2
    public static final int ShootT_BulCount_w = 4;                 // 4, 2
    public static final int ShootT_SFX_w = 6;                      // 6, 2
    public static final int ShootT_SizeOf_l = 8;                   // 8

    // Alien Data Definition — STRUCTURE AlienT,0
    public static final int AlienT_GFXType_w = 0;                  //  0, 2
    public static final int AlienT_DefaultBehaviour_w = 2;         //  2, 2
    public static final int AlienT_ReactionTime_w = 4;             //  4, 2
    public static final int AlienT_DefaultSpeed_w = 6;             //  6, 2
    public static final int AlienT_ResponseBehaviour_w = 8;        //  8, 2
    public static final int AlienT_ResponseSpeed_w = 10;           // 10, 2
    public static final int AlienT_ResponseTimeout_w = 12;         // 12, 2
    public static final int AlienT_DamageToRetreat_w = 14;         // 14, 2
    public static final int AlienT_DamageToFollowup_w = 16;        // 16, 2
    public static final int AlienT_FollowupBehaviour_w = 18;       // 18, 2
    public static final int AlienT_FollowupSpeed_w = 20;           // 20, 2
    public static final int AlienT_FollowupTimeout_w = 22;         // 22, 2
    public static final int AlienT_RetreatBehaviour_w = 24;        // 24, 2
    public static final int AlienT_RetreatSpeed_w = 26;            // 26, 2
    public static final int AlienT_RetreatTimeout_w = 28;          // 28, 2
    public static final int AlienT_BulType_w = 30;                 // 30, 2
    public static final int AlienT_HitPoints_w = 32;               // 32, 2
    public static final int AlienT_Height_w = 34;                  // 34, 2
    public static final int AlienT_Girth_w = 36;                   // 36, 2
    public static final int AlienT_SplatType_w = 38;               // 38, 2 - either the projectile class, or spawned alien class
    public static final int AlienT_Auxilliary_w = 40;              // 40, 2
    public static final int AlienT_SizeOf_l = 42;                  // 42

    // Object Data Definition — STRUCTURE ODefT,0
    public static final int ODefT_Behaviour_w = 0;                 //  0, 2
    public static final int ODefT_GFXType_w = 2;                   //  2, 2
    public static final int ODefT_ActiveTimeout_w = 4;             //  4, 2
    public static final int ODefT_HitPoints_w = 6;                 //  6, 2
    public static final int ODefT_ExplosiveForce_w = 8;            //  8, 2 unused
    public static final int ODefT_Impassible_w = 10;               // 10, 2 unused
    public static final int ODefT_DefaultAnimLen_w = 12;           // 12, 2 unused
    public static final int ODefT_CollideRadius_w = 14;            // 14, 2
    public static final int ODefT_CollideHeight_w = 16;            // 16, 2
    public static final int ODefT_FloorCeiling_w = 18;             // 18, 2
    public static final int ODefT_LockToWall_w = 20;               // 20, 2 unused
    public static final int ODefT_ActiveAnimLen_w = 22;            // 22, 2 unused
    public static final int ODefT_SFX_w = 24;                      // 24, 2
    public static final int ODefT_SizeOf_l = 40;                   // 40 (PADDING 14 après SFX)

    public static final int OBJ_TYPE_ALIEN = 0;
    public static final int OBJ_TYPE_OBJECT = 1;
    public static final int OBJ_TYPE_PROJECTILE = 2;
    public static final int OBJ_TYPE_AUX = 3;
    public static final int OBJ_TYPE_PLAYER1 = 4;
    public static final int OBJ_TYPE_PLAYER2 = 5;

    // Runtime objects are 64 byte structures. The first 18 bytes are common, but the
    // remainder depend on what the type of the object is. — STRUCTURE ObjT,0
    public static final int ObjT_XPos_l = 0;                       // 0, 4 - To be confirmed
    public static final int ObjT_ZPos_l = 4;                       // 4, 4 - To be confirmed
    public static final int ObjT_YPos_l = 8;                       // 8, 4 - To be confirmed
    public static final int ObjT_ZoneID_w = 12;                    // 12, 2 - Zone where the object is located, or -1 if removed
    // PADDING 2 - Unknown
    public static final int ObjT_TypeID_b = 16;                    // 16 - Defines the type (alien, bullet, object etc.)
    public static final int ObjT_SeePlayer_b = 17;                 // 17 - Line of sight to player
    public static final int ObjT_Header_SizeOf_l = 18;             // 18 - After here, depends on ObjT_TypeID_b
    public static final int ObjT_SizeOf_l = 64;                    // 64

    public static final int OBJ_PREV = -ObjT_SizeOf_l;             // object before current
    public static final int OBJ_NEXT = ObjT_SizeOf_l;              // object after current

    // MACRO NEXT_OBJ : add.w #ObjT_SizeOf_l,aN  →  aN += ObjT_SizeOf_l
    // MACRO PREV_OBJ : sub.w #ObjT_SizeOf_l,aN  →  aN -= ObjT_SizeOf_l

    // Runtime entity extension for ObjT — STRUCTURE EntT,ObjT_Header_SizeOf_l
    public static final int EntT_HitPoints_b = 18;                 // 18, 1
    public static final int EntT_DamageTaken_b = 19;               // 19, 1
    public static final int EntT_CurrentMode_b = 20;               // 20, 1
    public static final int EntT_TeamNumber_b = 21;                // 21, 1
    public static final int EntT_CurrentSpeed_w = 22;              // 22, 2 unused
    public static final int EntT_DisplayText_w = 24;               // 24, 2
    public static final int EntT_ZoneID_w = 26;                    // 26, 2 - todo: relation avec ObjT_ZoneID_w ?
    public static final int EntT_CurrentControlPoint_w = 28;       // 28, 2
    public static final int EntT_CurrentAngle_w = 30;              // 30, 2
    public static final int EntT_TargetControlPoint_w = 32;        // 32, 2
    public static final int EntT_Timer1_w = 34;                    // 34, 2
    public static final int EntT_EnemyFlags_l = 36;                // 36, 4
    public static final int EntT_Timer2_w = 40;                    // 40, 2
    public static final int EntT_ImpactX_w = 42;                   // 42, 2
    public static final int EntT_ImpactZ_w = 44;                   // 44, 2
    public static final int EntT_ImpactY_w = 46;                   // 46, 2
    public static final int EntT_VelocityY_w = 48;                 // 48, 2

    // Union
    public static final int EntT_DoorsAndLiftsHeld_l = 50;         // 50, 4 - actually accessed as a long
    public static final int EntT_Timer3_w = 52;                    // 52, 2

    // union field of UWORD, UBYTE[2]
    public static final int EntT_Timer4_w = 54;                    // 54, 0
    public static final int EntT_Type_b = 54;                      // 54, 1
    public static final int EntT_WhichAnim_b = 55;                 // 55, 1
    public static final int EntT_SizeOf_l = 64;                    // 64 - This is the actual size in memory

    public static final int ENT_TYPE_COLLECTABLE = 0;
    public static final int ENT_TYPE_ACTIVATABLE = 1;
    public static final int ENT_TYPE_DESTRUCTABLE = 2;
    public static final int ENT_TYPE_DECORATION = 3;

    public static final int ENT_PREV_2 = -EntT_SizeOf_l * 2;       // entity two before current
    public static final int ENT_PREV = -EntT_SizeOf_l;             // entity before current
    public static final int ENT_NEXT = EntT_SizeOf_l;              // entity after current
    public static final int ENT_NEXT_2 = EntT_SizeOf_l * 2;        // entity two after current

    // Runtime projectile extension for ObjT — STRUCTURE ShotT,ObjT_Header_SizeOf_l
    public static final int ShotT_VelocityX_w = 18;                // 18, 2
    // PADDING 2                                                   // 20, 2
    public static final int ShotT_VelocityZ_w = 22;                // 22, 2
    // PADDING 4                                                   // 24, 4
    public static final int ShotT_Power_w = 28;                    // 28, 2
    public static final int ShotT_Status_b = 30;                   // 30, 1
    public static final int ShotT_Size_b = 31;                     // 31, 1
    // PADDING 10                                                  // 32, 10
    public static final int ShotT_VelocityY_w = 42;                // 42, 2

    // union
    public static final int ShotT_AccYPos_w = 44;                  // 44, 0
    public static final int ShotT_AuxOffsetX_w = 44;               // 44, 2
    public static final int ShotT_AuxOffsetY_w = 46;               // 46, 2
    // PADDING 4                                                   // 48, 4
    public static final int ShotT_Anim_b = 52;                     // 52, 1
    // PADDING 1                                                   // 53, 1
    public static final int ShotT_Gravity_w = 54;                  // 54, 2
    public static final int ShotT_Impact_w = 56;                   // 56, 2
    public static final int ShotT_Lifetime_w = 58;                 // 58, 2
    public static final int ShotT_Flags_w = 60;                    // 60, 2
    public static final int ShotT_Worry_b = 62;                    // 62, 1
    public static final int ShotT_InUpperZone_b = 63;              // 63, 1
    public static final int ShotT_SizeOf_l = 64;                   // 64

    // Zone Structure — STRUCTURE ZoneT,0
    // (NB: le commentaire ASM ";  2, 2" sur ZoneT_ID_w est faux, l'offset réel est 0)
    public static final int ZoneT_ID_w = 0;                        //  0, 2
    public static final int ZoneT_Floor_l = 2;                     //  2, 4
    public static final int ZoneT_Roof_l = 6;                      //  6, 4
    public static final int ZoneT_UpperFloor_l = 10;               // 10, 4
    public static final int ZoneT_UpperRoof_l = 14;                // 14, 4
    public static final int ZoneT_Water_l = 18;                    // 18, 4
    public static final int ZoneT_Brightness_w = 22;               // 22, 2
    public static final int ZoneT_UpperBrightness_w = 24;          // 24, 2
    public static final int ZoneT_ControlPoint_w = 26;             // 26, 2 really UBYTE[2]
    public static final int ZoneT_BackSFXMask_w = 28;              // 28, 2 Originally long but always accessed as word
    public static final int ZoneT_Unused_w = 30;                   // 30, 2 so this is the unused half
    public static final int ZoneT_EdgeListOffset_w = 32;           // 32, 2 Offset relative to ZoneT instance
    public static final int ZoneT_Points_w = 34;                   // 34, 2
    public static final int ZoneT_DrawBackdrop_b = 36;             // 36, 1 Draw background?
    public static final int ZoneT_Echo_b = 37;                     // 37, 1
    public static final int ZoneT_TelZone_w = 38;                  // 38, 2
    public static final int ZoneT_TelX_w = 40;                     // 40, 2
    public static final int ZoneT_TelZ_w = 42;                     // 42, 2
    public static final int ZoneT_FloorNoise_w = 44;               // 44, 2
    public static final int ZoneT_UpperFloorNoise_w = 46;          // 46, 2
    public static final int ZoneT_PotVisibleZoneList_vw = 48;      // 48, 2 - Set of PVS zones (array of 4-word tuples)
    public static final int ZoneT_SizeOf_l = 50;                   // 50

    // ZPVSRecord (tuple PVS) — 4 mots (zone.h)
    public static final int ZPVSRecordT_ZoneID_w = 0;              //  0, 2
    public static final int ZPVSRecordT_ClipID_w = 2;              //  2, 2
    public static final int ZPVSRecordT_Word2_w = 4;               //  4, 2
    public static final int ZPVSRecordT_Word3_w = 6;               //  6, 2
    public static final int ZPVSRecordT_SizeOf_l = 8;              //  8

    // Edge structure — STRUCTURE EdgeT,0
    public static final int EdgeT_XPos_w = 0;                      //  0 X coordinate
    public static final int EdgeT_ZPos_w = 2;                      //  2 Z coordinate
    public static final int EdgeT_XLen_w = 4;                      //  4 Length in X direction
    public static final int EdgeT_ZLen_w = 6;                      //  6 Length in Z direction
    public static final int EdgeT_JoinZone_w = 8;                  //  8 Zone the edge joins to, or -1 for a solid wall
    public static final int EdgeT_Word_5 = 10;                     // 10 TODO
    public static final int EdgeT_Byte_12 = 12;                    // 12
    public static final int EdgeT_Byte_13 = 13;                    // 13
    public static final int EdgeT_Flags_w = 14;                    // 14 TODO - some sort of flags
    public static final int EdgeT_SizeOf_l = 16;                   // 16

    // Vec2W (math25d.h) — vecteur XZ 16 bits
    public static final int Vec2W_X = 0;                           //  0, 2
    public static final int Vec2W_Z = 2;                           //  2, 2
    public static final int Vec2W_SizeOf = 4;                      //  4

    // ZEdgeInfo (zone.h)
    public static final int ZEdgeInfoT_EdgeID_w = 0;              //  0, 2
    public static final int ZEdgeInfoT_StartPointID_w = 2;        //  2, 2
    public static final int ZEdgeInfoT_EndPointID_w = 4;          //  4, 2
    public static final int ZEdgeInfoT_Reserved_w = 6;           //  6, 2
    public static final int ZEdgeInfoT_SizeOf_l = 8;             //  8

    // ZEdgePVSHeader (zone.h) — en-tête PVS par arête + ZEdgeInfo[1]
    public static final int ZEdgePVSHeaderT_ZoneID_w = 0;        //  0, 2
    public static final int ZEdgePVSHeaderT_ListSize_w = 2;      //  2, 2
    public static final int ZEdgePVSHeaderT_EdgeCount_w = 4;     //  4, 2
    public static final int ZEdgePVSHeaderT_ZoneMaskOffset_w = 6; //  6, 2
    public static final int ZEdgePVSHeaderT_DoorMaskOffset_w = 8; //  8, 2
    public static final int ZEdgePVSHeaderT_LiftMaskOffset_w = 10; // 10, 2
    public static final int ZEdgePVSHeaderT_EdgeInfoList_v = 12;  // 12 - ZEdgeInfo[1]
    public static final int ZEdgePVSHeaderT_SizeOf_l = 20;       // 12 + sizeof(ZEdgeInfo)=8

    // ZDoorListMask = UWORD (zone.h)
    public static final int ZDoorListMask_SizeOf = 2;            //  2

    // STRUCTURE PVST,0
    public static final int PVST_Zone_w = 0;                       // 0
    public static final int PVST_ClipID_w = 2;                     // 2
    public static final int PVST_Word_2 = 4;                       // 4 TODO
    public static final int PVST_Word_3 = 6;                       // 6 TODO
    public static final int PVST_SizeOf_l = 8;                     // 8

    public static final int NUM_PLR_SHOT_DATA = 20;
    public static final int NUM_ALIEN_SHOT_DATA = 20;

    // **************************
    // * Game link file offsets *
    // **************************

    public static final int O_FrameStoreSize = 6;
    public static final int O_AnimSize = O_FrameStoreSize * 20;    // 120
    public static final int AmmoGiveLen = 22 * 2;                  // 44
    public static final int GunGiveLen = 12 * 2;                   // 24
    public static final int A_FrameLen = 11;
    public static final int A_OptLen = A_FrameLen * 20;            // 220
    public static final int A_AnimLen = A_OptLen * 11;             // 2420

    public static final int GLFT_OBJ_NAME_LENGTH = 20;
    public static final int GLFT_GUN_NAME_LENGTH = 20;
    public static final int GLFT_BUL_NAME_LENGTH = 20;

    // Game Link File Offsets — STRUCTURE GLFT,64 (les 64 premiers octets sont l'en-tête)
    public static final int GLFT_LevelNames_l = 64;                // NUM_LEVELS*40 = 640
    public static final int GLFT_ObjGfxNames_l = 704;              // NUM_OBJECT_DEFS*64 = 1920
    public static final int GLFT_SFXFilenames_l = 2624;            // NUM_SFX*60 = 3840
    public static final int GLFT_FloorFilename_l = 6464;           // 64
    public static final int GLFT_TextureFilename_l = 6528;         // 192
    public static final int GLFT_GunGFXFilename_l = 6720;          // 64
    public static final int GLFT_StoryFilename_l = 6784;           // 64
    public static final int GLFT_BulletDefs_l = 6848;              // NUM_BULLET_DEFS*BulT_SizeOf_l = 6000
    public static final int GLFT_BulletNames_l = 12848;            // NUM_BULLET_DEFS*GLFT_BUL_NAME_LENGTH = 400
    public static final int GLFT_GunNames_l = 13248;               // NUM_GUN_DEFS*GLFT_GUN_NAME_LENGTH = 200
    public static final int GLFT_ShootDefs_l = 13448;              // NUM_GUN_DEFS*ShootT_SizeOf_l = 80
    public static final int GLFT_AlienNames_l = 13528;             // NUM_ALIEN_DEFS*20 = 400
    public static final int GLFT_AlienDefs_l = 13928;              // NUM_ALIEN_DEFS*AlienT_SizeOf_l = 840
    public static final int GLFT_FrameData_l = 14768;              // 7680 - todo: figure out how this is derived
    public static final int GLFT_ObjectNames_l = 22448;            // NUM_OBJECT_DEFS*GLFT_OBJ_NAME_LENGTH = 600
    public static final int GLFT_ObjectDefs = 23048;               // NUM_OBJECT_DEFS*ODefT_SizeOf_l = 1200
    public static final int GLFT_ObjectDefAnims_l = 24248;         // NUM_OBJECT_DEFS*O_AnimSize = 3600
    public static final int GLFT_ObjectActAnims_l = 27848;         // NUM_OBJECT_DEFS*O_AnimSize = 3600
    public static final int GLFT_AmmoGive_l = 31448;               // NUM_OBJECT_DEFS*AmmoGiveLen = 1320 ; ammo per collectable
    public static final int GLFT_GunGive_l = 32768;                // NUM_OBJECT_DEFS*GunGiveLen = 720 ; guns per collectable
    public static final int GLFT_AlienAnims_l = 33488;             // NUM_ALIEN_DEFS*A_AnimLen = 48400
    public static final int GLFT_VectorNames_l = 81888;            // NUM_OBJECT_DEFS*64 = 1920
    public static final int GLFT_WallGFXNames_l = 83808;           // NUM_WALL_TEXTURES*64 = 1024
    public static final int GLFT_WallHeights_l = 84832;            // NUM_WALL_TEXTURES*2 = 32
    public static final int GLFT_AlienBrights_l = 84864;           // NUM_ALIEN_DEFS*2 = 40
    public static final int GLFT_GunObjects_l = 84904;             // NUM_GUN_DEFS*2 = 20
    public static final int GLFT_Player1Graphic_w = 84924;         // 2
    public static final int GLFT_Player2Graphic_w = 84926;         // 2
    public static final int GLFT_FloorData_l = 84928;              // 16*4 = 64 ; MSW is damage, LSW is sound effect
    public static final int GLFT_AlienShootDefs_l = 84992;         // NUM_ALIEN_DEFS*ShootT_SizeOf_l = 160
    public static final int GLFT_AmbientSFX_l = 85152;             // 16*2 = 32
    public static final int GLFT_LevelMusic_l = 85184;             // NUM_LEVELS*64 = 1024
    public static final int GLFT_EchoTable_l = 86208;              // 60
    public static final int GLFT_SizeOf_l = 86268;

    public static final int NUM_INVENTORY_ITEMS = NUM_GUN_DEFS + 2;          // 12
    public static final int NUM_INVENTORY_CONSUMABLES = NUM_BULLET_DEFS + 2; // 22

    public static final int MAX_ACHIEVEMENTS = 128;

    // Inventory consumables (health/fuel/ammo) — STRUCTURE InvCT,0
    public static final int InvCT_Health_w = 0;                    // 2
    public static final int InvCT_JetpackFuel_w = 2;               // 2
    public static final int InvCT_AmmoCounts_vw = 4;               // 40 - UWORD[NUM_BULLET_DEFS]
    public static final int InvCT_SizeOf_l = 44;                   // 44

    // Inventory items (weapons/jetpack/shield) — STRUCTURE InvIT,0
    public static final int InvIT_Shield_w = 0;                    // 2
    public static final int InvIT_JetPack_w = 2;                   // 2
    public static final int InvIT_Weapons_vw = 4;                  // 20 - UWORD[NUM_GUN_DEFS]
    public static final int InvIT_SizeOf_l = 24;                   // 24

    // Full Inventory (player/collectable) — STRUCTURE InvT,0
    public static final int InvT_Consumables = 0;                  // 44
    public static final int InvT_Items = 44;                       // 24
    public static final int InvT_SizeOf_l = 68;                    // 68

    // Custom game properties — STRUCTURE GModT,0
    // (STRUCTURE GModT_MaxInv,(InvCT_SizeOf_l) : la macro STRUCTURE définit le
    //  nom à 0 et place SOFFSET à InvCT_SizeOf_l — le bloc MaxInv occupe 0..43)
    public static final int GModT_MaxInv = 0;                      // 44
    public static final int GModT_NumAchievements = 44;            // 2
    public static final int GModT_AchievementSize = 46;            // 2
    public static final int GModT_SizeOf_l = 48;                   // 48

    // Game statistics — STRUCTURE GStatT,0
    public static final int GStatT_MaxInv = 0;                     // 44 - Progressed inventory limits
    public static final int GStatT_LevelBestTimes_vl = 44;         // 64 - ULONG[NUM_LEVELS] - best time per level
    public static final int GStatT_LevelPlayCounts_vw = 108;       // 32 - UWORD[NUM_LEVELS] - times attempted
    public static final int GStatT_LevelWonCounts_vw = 140;        // 32 - UWORD[NUM_LEVELS] - times beaten
    public static final int GStatT_LevelFailCounts_vw = 172;       // 32 - UWORD[NUM_LEVELS] - times killed
    public static final int GStatT_LevelImprovedTimeCounts_vw = 204; // 32 - UWORD[NUM_LEVELS] - best time improvements
    public static final int GStatT_AlienKills_vw = 236;            // 40 - UWORD[NUM_ALIEN_DEFS] - kills by type
    public static final int GStatT_TotalHealthCollected_w = 276;   // 4
    public static final int GStatT_TotalFuelCollected_w = 280;     // 4
    public static final int GStatT_TotalAmmoFound_vw = 284;        // 80 - ULONG[NUM_BULLET_DEFS]
    public static final int GStatT_Achieved_vb = 364;              // MAX_ACHIEVEMENTS/8 = 16
    public static final int GStatT_SizeOf_l = 380;

    // Achievement (game.h) — AchievementStruct
    public static final int AchievementT_Name_l = 0;              //  0, 4 (ptr/offset chaîne)
    public static final int AchievementT_RewardDesc_l = 4;       //  4, 4 (ptr/offset chaîne)
    public static final int AchievementT_RuleMask_w = 8;         //  8, 2
    public static final int AchievementT_RuleId_w = 10;          // 10, 2
    public static final int AchievementT_RuleParams_vb = 12;     // 12, 8 (union de paramètres)
    public static final int AchievementT_HealthCapBonus_w = 20;  // 20, 2
    public static final int AchievementT_HealthBonus_w = 22;     // 22, 2
    public static final int AchievementT_FuelCapBonus_w = 24;    // 24, 2
    public static final int AchievementT_AmmoType_w = 26;        // 26, 2 (WORD signé, -1 = aucun)
    public static final int AchievementT_AmmoTypeCapBonus_w = 28; // 28, 2
    public static final int AchievementT_AmmoTypeBonus_w = 30;   // 30, 2
    public static final int AchievementT_SizeOf_l = 32;          // 32

    public static final int GAME_EVENTBIT_KILL = 0;
    public static final int GAME_EVENTBIT_ZONE_CHANGE = 1;
    public static final int GAME_EVENTBIT_LEVEL_START = 2;
    public static final int GAME_EVENTBIT_ADD_INVENTORY = 3;

    // *****************************
    // * Door Definitions **********
    // *****************************

    public static final int DR_Plr_SPC = 0;
    public static final int DR_Plr = 1;
    public static final int DR_Bul = 2;
    public static final int DR_Alien = 3;
    public static final int DR_Timeout = 4;
    public static final int DR_Never = 5;
    public static final int DL_Timeout = 0;
    public static final int DL_Never = 1;

    public static final int LVLT_MESSAGE_LENGTH = 160;
    public static final int LVLT_MESSAGE_COUNT = 10;

    // Maximum number of zones. Note that the game doesn't yet support this limit fully.
    public static final int LVL_EXPANDED_MAX_ZONE_COUNT = 512;

    // Maximum number of zones. Once this is fully working, redefine as LVL_EXPANDED_MAX_ZONE_COUNT
    public static final int LVL_MAX_ZONE_COUNT = 256;

    public static final int LVL_MAX_DOOR_ZONES = 16;
    public static final int LVL_MAX_LIFT_ZONES = 16;

    //
    // LEVEL DATA FILES
    //
    // twolev.bin data header, after the text messages — STRUCTURE TLBT,0
    // (noms verbatim : les six premiers labels portent la coquille TBLT_ de l'original)
    public static final int TBLT_Plr1_StartXPos_w = 0;             // 0
    public static final int TBLT_Plr1_StartZPos_w = 2;             // 2
    public static final int TBLT_Plr1_StartZoneID_w = 4;           // 4
    public static final int TBLT_Plr2_StartXPos_w = 6;             // 6
    public static final int TBLT_Plr2_StartZPos_w = 8;             // 8
    public static final int TBLT_Plr2_StartZoneID_w = 10;          // 10
    public static final int TLBT_NumControlPoints_w = 12;          // 12
    public static final int TLBT_NumPoints_w = 14;                 // 14
    public static final int TLBT_NumZones_w = 16;                  // 16
    public static final int TLBT_Unknown_w = 18;                   // 18
    public static final int TLBT_NumObjects_w = 20;                // 20
    public static final int TLBT_PointsOffset_l = 22;              // 22
    public static final int TLBT_FloorLineOffset_l = 26;           // 26
    public static final int TLBT_ObjectDataOffset_l = 30;          // 30
    public static final int TLBT_ShotDataOffset_l = 34;            // 34 - this in twolev.bin ?
    public static final int TLBT_AlienShotDataOffset_l = 38;       // 38 - this in twolev.bin ?
    public static final int TLBT_ObjectPointsOffset_l = 42;        // 42
    public static final int TLBT_Plr1ObjectOffset_l = 46;          // 46
    public static final int TLBT_Plr2ObjectOffset_l = 50;          // 50
    public static final int TLBT_SizeOf_l = 54;                    // This is the end of the header

    // twolev.graph.bin data header — STRUCTURE TLGT,0
    public static final int TLGT_DoorDataOffset_l = 0;             // 0
    public static final int TLGT_LiftDataOffset_l = 4;             // 4
    public static final int TLGT_SwitchDataOffset_l = 8;           // 8
    public static final int TLGT_ZoneGraphAddsOffset_l = 12;       // 12
    public static final int TLGT_ZoneAddsOffset_l = 16;            // 16
    public static final int TLGT_SizeOf_l = 20;

    // Level Data Structure (after message block) — STRUCTURE LvlT,0
    public static final int LvlT_Plr1_StartX_w = 0;                // 0, 2
    public static final int LvlT_Plr1_StartZ_w = 2;                // 2, 2
    public static final int LvlT_Plr1_Start_ZoneID_w = 4;          // 4, 2
    public static final int LvlT_Plr2_StartX_w = 6;                // 6, 2
    public static final int LvlT_Plr2_StartZ_w = 8;                // 8, 2
    public static final int LvlT_Plr2_Start_ZoneID_w = 10;         // 10, 2
    public static final int LvlT_NumControlPoints_w = 12;          // 12, 2
    public static final int LvlT_NumPoints_w = 14;                 // 14, 2
    public static final int LvlT_NumZones_w = 16;                  // 16, 2
    public static final int LvlT_Unk_0_w = 18;                     // 18, 2
    public static final int LvlT_NumObjectPoints_w = 20;           // 20, 2
    // Offset values are typically measured relative to the start of the file (inc message block)
    public static final int LvlT_OffsetToPoints_l = 22;            // 22, 4
    public static final int LvlT_OffsetToFloorLines_l = 26;        // 26, 4
    public static final int LvlT_OffsetToObjects_l = 30;           // 30, 4
    public static final int LvlT_OffsetToPlayerShot_l = 34;        // 34, 4
    public static final int LvlT_OffsetToAlienShot_l = 38;         // 38, 4
    public static final int LvlT_OffsetToObjectPoints_l = 42;      // 42, 4
    public static final int LvlT_OffsetToPlr1Obj_l = 46;           // 46, 4
    public static final int LvlT_OffsetToPlr2Obj_l = 50;           // 50, 4
    public static final int LvlT_ControlPointCoords_vw = 54;       // 54
    public static final int LvlT_SizeOf_l = 54;

    // Door Data Structure — STRUCTURE ZLiftableT,0
    // NB: dans defs.i, GraphicsPtrOffset est déclaré UWORD (ce qui ne réserverait
    // que 2 octets) mais le champ fait réellement 4 octets : c/defs.h /
    // zone_liftable.h (zl_GraphicsOffset LONG à 26, zl_ZoneID à 30, taille 36)
    // fait foi — les offsets ASM de cette structure ne sont référencés nulle part.
    public static final int ZLiftableT_Bottom_w = 0;               //  0, 2
    public static final int ZLiftableT_Top_w = 2;                  //  2, 2
    public static final int ZLiftableT_OpeningSpeed_w = 4;         //  4, 2
    public static final int ZLiftableT_ClosingSpeed_w = 6;         //  6, 2
    public static final int ZLiftableT_OpenDuration_w = 8;         //  8, 2
    public static final int ZLiftableT_OpeningSoundFX_w = 10;      // 10, 2
    public static final int ZLiftableT_ClosingSoundFX_w = 12;      // 12, 2
    public static final int ZLiftableT_OpenedSoundFX_w = 14;       // 14, 2
    public static final int ZLiftableT_ClosedSoundFX_w = 16;       // 16, 2
    public static final int ZLiftableT_Word9_w = 18;               // 18, 2 - something X coordinate related
    public static final int ZLiftableT_Word10_w = 20;              // 20, 2 - something Z coordinate related
    public static final int ZLiftableT_Word11_w = 22;              // 22, 2
    public static final int ZLiftableT_Word12_w = 24;              // 24, 2
    public static final int ZLiftableT_GraphicsPtrOffset_l = 26;   // 26, 4 - offset from Lvl_GraphicsPtr_l
    public static final int ZLiftableT_ZoneID_w = 30;              // 30, 2
    public static final int ZLiftableT_Word16_w = 32;              // 32, 2
    public static final int ZLiftableT_RaiseCondition_b = 34;      // 34, 1
    public static final int ZLiftableT_LowerCondition_b = 35;      // 35, 1
    public static final int ZLiftableT_SizeOf_l = 36;              // 36

    // For two player victory messages
    public static final int GAME_DM_VICTORY_MESSAGE_LENGTH = 80;

    // For in game option messages
    public static final int OPTS_MESSAGE_LENGTH = 40;

    public static final int MSG_TAG_NARRATIVE = 0;
    public static final int MSG_TAG_DEFAULT = 1 << 14;
    public static final int MSG_TAG_OPTIONS = 2 << 14;
    public static final int MSG_TAG_OTHER = 3 << 14;

    // Other stuff

    public static final int SKY_BACKDROP_W = 648;
    public static final int SKY_BACKDROP_H = 240;

    // Rendering Stuff
    // Data structure used by wall drawing — STRUCTURE WD,0
    public static final int WD_DWidth_l = 0;                       //  0 ; union
    public static final int WD_LeftX_w = 0;                        //  0
    public static final int WD_RightX_w = 2;                       //  2

    public static final int WD_DBM_l = 4;                          //  4 ; union
    public static final int WD_LeftBM_w = 4;                       //  4
    public static final int WD_RightBM_w = 6;                      //  6

    public static final int WD_DDist_l = 8;                        //  8 ; union
    public static final int WD_LeftDist_w = 8;                     //  8
    public static final int WD_RightDist_w = 10;                   // 10

    public static final int WD_DTop_l = 12;                        // 12 ; union
    public static final int WD_LeftTop_w = 12;                     // 12
    public static final int WD_RightTop_w = 14;                    // 14

    public static final int WD_DBot_l = 16;                        // 16 ; union
    public static final int WD_LeftBot_w = 16;                     // 16
    public static final int WD_RightBot_w = 18;                    // 18

    public static final int WD_Unknown_0_w = 20;                   // 20
    public static final int WD_Unknown_1_w = 22;                   // 22

    // Whole wall for simple case, lower half for full Gouraud case
    public static final int WD_LeftBrightScaled_l = 24;            // 24 ; union
    public static final int WD_LeftBright_w = 24;                  // 24
    public static final int WD_RightBright_w = 26;                 // 26

    public static final int WD_DHorizBright_l = 28;                // 28

    public static final int WD_UpperLeftBrightScaled_l = 32;       // 32 ; union
    public static final int WD_UpperLeftBright_w = 32;             // 32
    public static final int WD_UpperRightBright_w = 34;            // 34

    public static final int WD_DUpperHorizBright_l = 36;           // 36

    public static final int WD_SizeOf_l = 40;
}
